# Request

---
# Response
bool response 
string message
float64 weed_x
float64 weed_y
float64 weed_z
float64 weed_height
float64 weed_radius
float64[] asparagus # [x1,y1,z1,h1,r1,x2,...,xn,yn,zn,rn,hn]